pure_pursuit_odom:
  ros__parameters:
    global_frame: "odom"
    robot_frame: "base_link"
    action_name: "follow_path_odom"

    max_linear_vel: 5.0
    accel_limit: 1.0

    min_lookahead_dist: 0.2
    lookahead_gain: 0.2

    max_angular_vel: 2.0
    kp_yaw: 2.0

    goal_tolerance: 0.05
    yaw_tolerance: 0.03
    min_vel_enforce_dist: 0.15 #この距離までは、減速範囲内でも最低速度は維持する

    v_start_min: 0.4
    decel_start_dist: 0.4
    control_frequency: 20.0

    # --- その他設定（必要に応じてプログラム側で追加・利用可能） ---
    use_sim_time: False
